/**
 * AI Scoring Constants
 *
 * All scoring weights used by AI strategies.
 * Higher positive = more desirable, negative = less desirable.
 */

/** Card rank values and thresholds */
export const RANK = {
  JACK: 11,
  QUEEN: 12,
  KING: 13,
  ACE: 14,
  LOW_THRESHOLD: 4,
  MID_RANGE_MIN: 7,
  MID_RANGE_MAX: 10,
  HIGH_THRESHOLD: 11,
  BLUFF_MIN: 9,
} as const;

/** Game phase thresholds */
export const THRESHOLDS = {
  LATE_GAME_TRICKS: 8,
  EARLY_GAME_TRICKS: 4,
  PROTECTED_SUIT_SIZE: 4,
  MIN_LOW_CARDS_FOR_PROTECTION: 3,
  CRITICAL_LOW_SPADE_COUNT: 2,
  MOON_HEARTS_WITH_QUEEN: 6,
  MOON_HEARTS_WITHOUT_QUEEN: 10,
  WINNING_LEAD_MARGIN: 20,
  MOON_EARLY_GAME_TRICKS: 5,
  MOON_MID_GAME_TRICKS: 9,
} as const;

/** Passing phase scoring */
export const PASS_SCORES = {
  QUEEN_OF_SPADES_UNPROTECTED: 100,
  QUEEN_OF_SPADES_PROTECTED: 30,
  HEART_BASE: 20,
  PROTECTED_HIGH_CARD: -20,
  CRITICAL_SPADE_DEFENSE: -30,
  VOID_OPPORTUNITY: 25,
  WELL_PROTECTED_HIGH: -30,
  PROTECT_LEAD_DUMP_HIGH: 10,
  SPADE_DEFENSE_MULTIPLIER: 15,
  HIGH_SPADE_NO_QUEEN: 15,
  LOW_CARD_PROTECTION: -35,
  LOW_CARD_THRESHOLD: 6,
} as const;

/** Leading phase scoring */
export const LEAD_SCORES = {
  BASE: 100,
  RANK_PENALTY_MULTIPLIER: 3,
  STRATEGIC_LOW_HEART: 20,
  AVOID_HEARTS: -30,
  FISH_FOR_QUEEN: 15,
  PRESERVE_QUEEN_PROTECTION: -20,
  AVOID_HIGH_SPADES: -25,
  EARLY_SAFE_LEAD: 10,
  LOWEST_IN_SUIT: 15,
  BLUFF_LEAD: 20,
  MOON_PREVENTION: 10,
  TARGET_LEADER_HEARTS: 15,
  OPPONENT_VOID_HEARTS: -50,
  SAFE_LOWEST_HEART: 25,
  HARD_FISH_FOR_QUEEN: 20,
  HARD_PROTECT_OWNED_QUEEN: -30,
  OPPONENT_MIGHT_HAVE_HIGH: -5,
  OPPONENT_VOID_IN_SUIT: -15,
  MOON_SHOOTER_VOID: -20,
  HEARTS_NOT_BROKEN: -100,
  LOW_HEART_VOID_OPPONENTS: 10,
  HIGH_HEART_VOID_RISK: -20,
  LOW_HEART_LEAD: 15,
  HIGH_HEART_RISK: -15,
  MID_HEART: -5,
  NEVER_LEAD_QUEEN: -200,
  SAVE_SPADE_FOR_QUEEN: -20,
  HIGH_SPADE_CATCH_QUEEN: -25,
  OPPONENT_VOID_MULTIPLIER: -15,
  OPPONENT_HIGH_CARDS_MULTIPLIER: 10,
  SAFE_LOW_LEAD: 15,
} as const;

/** Following phase scoring */
export const FOLLOW_SCORES = {
  BASE: 100,
  TRICK_1_SAFE_WIN: 20,
  TRICK_1_RANK_MULTIPLIER: 2,
  WIN_WITH_POINTS_BASE: -40,
  PENALTY_POINTS_MULTIPLIER: -5,
  SAFE_WIN_LAST_PLAYER: 10,
  RISK_OF_DUMP: -15,
  DUCK: 25,
  MOON_SHOT_TAKE: 50,
  STOP_MOON: 150,
  SAFE_WIN: 20,
  BLUFF_TAKE_SAFE: 15,
} as const;

/** Dumping phase scoring */
export const DUMP_SCORES = {
  BASE: 100,
  QUEEN_OF_SPADES: 200,
  HEART_BASE: 50,
  HEART_RANK_MULTIPLIER: 3,
  HIGH_CARD_RANK_MULTIPLIER: 2,
  KEEP_LOW_SPADE: -25,
  DUMP_ON_LEADER: 30,
  DONT_GIVE_QUEEN_TO_SHOOTER: -350,
  DONT_GIVE_HEARTS_TO_SHOOTER: -200,
  DUMP_ON_NON_SHOOTER: 250,
  HARD_KEEP_SPADE_QUEEN_OUT: -30,
  HARD_KEEP_LOW_SPADE: -10,
} as const;

/** Default AI behavior configuration */
export const DEFAULT_AI_CONFIG = {
  bluffProbability: 0.15,
  memoryTrickCount: 7,
  moonDetectionThreshold: 20,
  leaderPointThreshold: 15,
} as const;
